name: 'Powerscore CI/CD Pipeline'

on:
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:
    branches:
      - 'main'
      - 'develop'

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
      entryboard: ${{ steps.filter.outputs.entryboard }}
    steps:
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          backend:
            - 'backend/**'
          frontend:
            - 'frontend/**'
          entryboard:
            - 'powerscore-entryboard/**'
  backend:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - uses: actions/setup-go@v4
        name: Set up Go
        with:
          go-version-file: ./backend/go.mod
          check-latest: true
          cache-dependency-path: ./backend/go.sum

      - name: Build
        run: go build - ./
        working-directory: ./backend

      - name: Test
        run: go test -v ./
        working-directory: ./backend

  frontend:
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  entryboard:
    needs: changes
    if: ${{ needs.changes.outputs.entryboard == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4