name: 'Powerscore Main and Develop Branch CI/CD'

on:
  push:
    branches:
      - main
      - develop

env:
  NODE_VERSION: 20.x

jobs:
  Frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Run npm ci
        run: npm ci
        working-directory: ./frontend

      - name: Run npm build
        run: npm run build --if-present
        working-directory: ./frontend

      - name: Run npm test
        run: npm run test:unit
        working-directory: ./frontend

  Backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./backend/go.mod
          check-latest: true
          cache-dependency-path: ./backend/go.sum
      
      - name: Build
        run: go build -v ./
        working-directory: ./backend

      - name: Test
        run: go test ./... -coverprofile=cover.txt -covermode=atomic -coverpkg=./...
        working-directory: ./backend

      - name: Get Go Coverage
        uses: fgrosse/go-coverage-report@v1.0.2
        with:
          coverage-file-name: './backend/coverage.txt'

  Entryboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Run npm ci
        run: npm ci
        working-directory: ./powerscore-entryboard

      - name: Run npm build
        run: npm run build --if-present
        working-directory: ./powerscore-entryboard

      - name: Run npm test
        run: npm run test:unit
        working-directory: ./powerscore-entryboard