name: 'Powerscore Backend CI/CD'

on:
  pull_request:
    paths:
      - backend
  push:
    branches:
      - main
      - develop

jobs:
  Backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./backend/go.mod
          check-latest: true
          cache-dependency-path: ./backend/go.sum
      
      - name: Build
        run: go build -v ./

      - name: Test
        run: go test -cover -coverprofile=coverage.txt ./...
