name: 'Powerscore Frontend CI/CD'

on:
  pull_request:
    paths: 
      - frontend
  push:
    branches:
      - main
      - develop

env:
  NODE_VERSION: 20.x

jobs:
  Frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Run npm ci
        run: npm ci

      - name: Run npm build
        run: npm run build --if-present

      - name: Run npm test
        run: npm run test:unit
